services:
  stamp-app:
    build: ./stamp-app
    command: uvicorn main:app --host:0.0.0.0 --port 80 --reload --log-config=logging-conf.yaml

    container_name: stamp-app
    ports:
      - 8080:80
    volumes:
      - ./stamp-app:/app

  catalog-api:
    build: ./stamp-catalog-api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload  --log-config=logging-conf.yaml
    container_name: catalog-api
    ports:
      - 8081:80
    volumes:
      - ./stamp-catalog-api:/app
