services:
  stamp-app:
    build: ./stamp-app
    container_name: stamp-app
    ports:
      - 8080:80
    volumes:
      - ./stamp-app:/app

  catalogue-api:
    build: ./stamp-catalogue-api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    container_name: catalogui-api
    ports:
      - 8081:80
    volumes:
      - ./stamp-catalogue-api:/app
