name: pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Enables this workflow to be manually run from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Assume Python 3.X is installed and install Python requirements
      - name: Install Python requirements
        run: |
            python --version
            pip install -r requirements.txt

      # Run Pytest tests for stamp-catalogue-api
      - name: Run pytest tests for stamp-catalogue-api
        run: |
            cd stamp-catalogue-api
            pytest -vs
