name: test-stamp-catalogue-api

on:
  push:
    branches: [ master ]

  # Enables this workflow to be manually run from the Actions tab
  workflow_dispatch:

jobs:
  push-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python requirements
        run: |
            cd stamp-catalogue-api
            pip install -r requirements.txt

      - name: Run flake8
        run: |
            cd stamp-catalogue-api
            flake8 --config flake8.conf

      - name: Run pytest tests for stamp-catalogue-api
        run: |
            cd stamp-catalogue-api
            pytest -vs -k 'not stamps_poste_1_image'
